### ISSUE TITLE
Rehike pre-init error occurred

### ISSUE THREAD

**Issue by pbcairo** [Rehike/Rehike#181]
```
Here are the details:

Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Unexpected wire type. in C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php:355 Stack trace: #0 C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(512): Google\Protobuf\Internal\Message->skipField(Object(Google\Protobuf\Internal\CodedInputStream), 55) #1 C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(811): Google\Protobuf\Internal\Message->parseFieldFromStream(55, Object(Google\Protobuf\Internal\CodedInputStream), NULL) ( ... ) #13 C:\xampp\htdocs\index.php(51): require('C:\\xampp\\htdocs...') #14 {main} thrown
```

tried to re-clone the repository but didn't work

**Comment by aubymori** [comment]
Fixed by 956ab3dc5b92b55ab51d38a3539622cb84148af2.

Closing...
