### ISSUE TITLE
Unable to access the home page, get a Uncaught TypeError

### ISSUE THREAD

**Issue by MexicanPB** [Rehike/Rehike#245]
I get this error when I am on the home page
 
```
Uncaught TypeError: Rehike\Util\WebV2Shelves::continuationToWeb(): Argument #1 ($continuation) must be of type string, null given, called in C:\xampp\htdocs\controllers\feed.php on line 82 and defined in C:\xampp\htdocs\modules\Rehike\Util\WebV2Shelves.php:30
Stack trace:
#0 C:\xampp\htdocs\controllers\feed.php(82): Rehike\Util\WebV2Shelves::continuationToWeb(NULL)
#1 C:\xampp\htdocs\controllers\feed.php(44): Rehike\Controller\core\NirvanaController@anonymous::whatToWatch(Object(stdClass))
#2 C:\xampp\htdocs\controllers\core\HitchhikerController.php(116): Rehike\Controller\core\NirvanaController@anonymous->onGet(Object(stdClass), Object(Rehike\ControllerV2\RequestMetadata))
#3 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(51): Rehike\Controller\core\HitchhikerController->get(Object(stdClass), '', Object(Rehike\ControllerV2\RequestMetadata))
#4 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(73): Rehike\ControllerV2\GetControllerInstance->_cv2WrappedCallControllerMethod('get', Array)
#5 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(209): Rehike\ControllerV2\GetControllerInstance->__call('get', Array)
#6 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(156): Rehike\ControllerV2\Router::pointerHandler('feed', 'get')
#7 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(26): Rehike\ControllerV2\Router::baseRequestMethod(Array, 'get')
#8 C:\xampp\htdocs\router.php(52): Rehike\ControllerV2\Router::get(Array)
#9 C:\xampp\htdocs\index.php(69): require('C:\\xampp\\htdocs...')
#10 {main}
  thrown
```

<img width="960" alt="image" src="https://user-images.githubusercontent.com/74111213/217681892-4b420ba5-cf4c-474d-8949-51e0832f4e48.png">

**Comment by YukisCoffee** [comment]
Not a Rehike issue, this is a YouTube global issue that occurs currently on the Polymer frontend and mobile apps too, among other platforms. There's nothing we can do about this other than wait.
